name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  GO_VERSION: '1.25.3'
  AWS_REGION: eu-west-1
  ECR_REPOSITORY_API: sre-case-study-api
  ECR_REPOSITORY_LAMBDA: sre-case-study-lambda
  ECS_SERVICE: sre-case-study-service
  ECS_CLUSTER: sre-case-study
  ECS_TASK_DEFINITION: sre-case-study-task
  LAMBDA_FUNCTION_NAME: sre-case-study-lambda

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: app/go.sum

      - name: Install go modules
        working-directory: ./app
        run: go mod download

      - name: Run Test
        working-directory: ./app
        run: go test -v -race ./...

  go-build:
    name: Go build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: app/go.sum

      - name: Install go modules
        working-directory: ./app
        run: go mod download

      - name: Build Api
        working-directory: ./app
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server ./cmd/server/main.go
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: ./app/server

      - name: Lambda Build
        working-directory: ./app
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap ./cmd/lambda/main.go
      
      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda
          path: ./app/bootstrap

  docker-build-and-push-api:
    name: Docker Build and Push Api Image to ECR
    runs-on: ubuntu-latest
    needs: go-build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: api

      - name: Build and Push
        working-directory: ./app
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY_API }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mv ../server .
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  docker-build-and-push-lambda:
    name: Docker Build and Push Lambda Image to ECR
    runs-on: ubuntu-latest
    needs: go-build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: lambda

      - name: Build and Push
        working-directory: ./app
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY_LAMBDA }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mv ../bootstrap .
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . -f Dockerfile.lambda
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy-api:
    name: Deploy Api to ECS
    runs-on: ubuntu-latest
    env:
      TF_VAR_image_tag: ${{ github.sha }}
    needs:
      - docker-build-and-push-api
      - docker-build-and-push-lambda
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.13.5

      - name: Terraform Init
        working-directory: ./infrastructure/terraform/sre-case-study-api
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infrastructure/terraform/sre-case-study-api
        run: terraform apply -auto-approve

      - name: Wait for Service Stability
        run: |
          aws ecs wait services-stable \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }}

  deploy-lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    env:
      TF_VAR_image_tag: ${{ github.sha }}
    needs:
      - docker-build-and-push-lambda
      - docker-build-and-push-api
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.13.5

      - name: Terraform Init
        working-directory: ./infrastructure/terraform/sre-case-study-lambda
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infrastructure/terraform/sre-case-study-lambda
        run: terraform apply -auto-approve

      - name: Verify Lambda Deployment
        run: |
          expected_image_tag="${{ github.sha }}"
          deployed_image_uri=$(aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --query 'Configuration.Code.ImageUri' --output text)
          if [[ "$deployed_image_uri" != *"$expected_image_tag"* ]]; then
            echo "Deployed image tag does not match expected tag."
            exit 1
          else
            echo "Lambda deployment verified successfully."
          fi
